const CONFIG_COMMENTS = {
    "api.apiDebug": "Whether to debug the HTTP API. When debugging is enabled, the content and reply of every HTTP request are printed",
    "api.secret": "Some sensitive HTTP APIs require a secret to be provided when accessed, otherwise the call is not authorized. If accessed via 127.0.0.1, the secret may be omitted",
    "api.snapRoot": "Root directory for saving snapshots. Snapshots are generated and retrieved via the HTTP API (/index/api/getSnap)",
    "api.defaultSnap": "Default snapshot image. After FFmpeg snapshot capture has started but the snapshot has not yet been generated, this preset default image can be returned",
    "api.downloadRoot": "Root directory of files accessible via the downloadFile HTTP interface. Multiple directories are supported, separated by a semicolon (;)",
    "api.legacyAuth": "Whether to use the legacy hardcoded-secret authentication mode. Enabled by default; when enabled, every HTTP interface request must pass the secret. After disabling legacy auth mode, you must first call the /index/api/login interface to log in",
    "api.mem_pic_capacity": "In-memory image cache capacity",
    "api.save_mem_pic": "Whether to save in-memory images",
    "api.modelRoot": "Root directory of model files",
    
    "ffmpeg.bin": "Path to the FFmpeg executable. Relative/absolute paths are supported",
    "ffmpeg.cmd": "Command template for FFmpeg to pull a stream and re-push it. This template can be used to set some re-encoding parameters",
    "ffmpeg.snap": "Command for FFmpeg to generate snapshots. You can modify this config to change snapshot resolution or quality",
    "ffmpeg.log": "Path of the FFmpeg log. If left empty, no FFmpeg log is generated. Can be a relative (relative to this executable's directory) or absolute path",
    "ffmpeg.restart_sec": "Auto-restart interval (seconds). Defaults to 0, meaning no auto-restart. Mainly used to avoid the desync phenomenon caused by long-running FFmpeg stream pulling",
    
    "protocol.modify_stamp": "Whether to enable frame-level timestamp override during protocol conversion. 0: use the source stream's absolute timestamp; 1: use the system timestamp when ZLMediaKit receives the data; 2: use the source stream's relative timestamp",
    "protocol.enable_audio": "Whether to enable audio during protocol conversion",
    "protocol.add_mute_audio": "Add AAC silent audio. This switch has no effect when audio is disabled",
    "protocol.auto_close": "When no one is watching, whether to close directly (instead of returning close via the on_none_reader hook)",
    "protocol.demux_frame": "Whether to demux ts/ps frames",
    "protocol.continue_push_ms": "After a push disconnects, it can reconnect and continue pushing within the timeout, so the player keeps playing. Set to 0 to disable this feature",
    "protocol.paced_sender_ms": "Smooth-sending timer interval, in milliseconds. Set to 0 to disable. When enabled, it affects CPU performance and increases memory usage",
    "protocol.enable_hls": "Whether to enable conversion to HLS (mpegts)",
    "protocol.enable_hls_fmp4": "Whether to enable conversion to HLS (fmp4)",
    "protocol.enable_mp4": "Whether to enable MP4 recording",
    "protocol.enable_rtsp": "Whether to enable conversion to rtsp/webrtc",
    "protocol.enable_rtmp": "Whether to enable conversion to rtmp/flv",
    "protocol.enable_ts": "Whether to enable conversion to http-ts/ws-ts",
    "protocol.enable_fmp4": "Whether to enable conversion to http-fmp4/ws-fmp4",
    "protocol.mp4_as_player": "Whether to treat MP4 recording as a viewer",
    "protocol.mp4_max_second": "MP4 segment size, in seconds",
    "protocol.mp4_save_path": "MP4 recording save path",
    "protocol.hls_save_path": "HLS recording save path",
    "protocol.hls_demand": "Whether the HLS protocol is generated on demand. If hls.segNum is set to 0 (meaning HLS recording), HLS will always be generated",
    "protocol.rtsp_demand": "Whether the rtsp[s] protocol is generated on demand",
    "protocol.rtmp_demand": "Whether the rtmp[s], http[s]-flv, ws[s]-flv protocols are generated on demand",
    "protocol.ts_demand": "Whether the http[s]-ts protocol is generated on demand",
    "protocol.fmp4_demand": "Whether the http[s]-fmp4, ws[s]-fmp4 protocols are generated on demand",
    "protocol.enable_transcode_mp4": "Whether to enable transcoded MP4 recording",
    
    "general.enableVhost": "Whether to enable virtual hosts",
    "general.flowThreshold": "Threshold for triggering the hook.on_flow_report event after a player or pusher disconnects. The event is triggered only after traffic exceeds this threshold, in KB",
    "general.maxStreamWaitMS": "Maximum wait time for playback, in milliseconds. When a player plays a stream that does not exist, ZLMediaKit will make the player wait at most maxStreamWaitMS milliseconds",
    "general.streamNoneReaderDelayMS": "Maximum wait time before triggering the hook.on_stream_none_reader event when a stream has no viewers, in milliseconds",
    "general.resetWhenRePlay": "For pull proxy, whether to delete the previous media stream data when the stream disconnects and reconnects successfully",
    "general.mergeWriteMS": "Merge-write cache size (in milliseconds). Merge-write means the server caches a certain amount of data before writing it to the socket all at once",
    "general.mediaServerId": "Unique server ID, used to distinguish which server triggered a hook",
    "general.wait_track_ready_ms": "Maximum time to wait for an uninitialized Track, in milliseconds. After timeout, uninitialized Tracks are ignored",
    "general.wait_audio_track_data_ms": "Maximum time to wait for the audio Track to receive data, in milliseconds. If it times out and no audio data is received at all, the audio Track is ignored",
    "general.wait_add_track_ms": "If a stream has only a single Track, wait at most this many milliseconds. If no data from other Tracks is received after timeout, it is treated as a single-Track stream",
    "general.unready_frame_cache": "If a Track is not ready, frame data is cached first, but with a maximum count limit to prevent memory overflow",
    "general.broadcast_player_count_changed": "Whether to enable broadcasting of the viewer-count-changed event. Set to 1 to enable, 0 to disable",
    "general.listen_ip": "IP of the bound local network interface",
    
    "hls.fileBufSize": "Buffer size for HLS file writing. Adjusting this parameter can improve file I/O performance",
    "hls.segDur": "Maximum HLS segment duration",
    "hls.segNum": "Number of HLS segments retained in the m3u8 index (actual retained count + segRetain). If set to 0, segments are not deleted and the m3u8 file records the full segment list",
    "hls.segDelay": "Number of delayed HLS segments. Greater than 0 will generate an hls_delay.m3u8 file; 0 will not generate it",
    "hls.segRetain": "Number of HLS segments kept on disk after being removed from the m3u8 file",
    "hls.broadcastRecordTs": "Whether to broadcast the HLS segment (ts/fmp4) completion notification (on_record_ts)",
    "hls.deleteDelaySec": "Deletion delay for live HLS files, in seconds",
    "hls.segKeep": "When this option is enabled, the m3u8 file still behaves as live, but segment files are all retained for VOD use",
    "hls.fastRegister": "If set to 1, the first segment length is forced to one GOP. When the GOP is smaller than segDur, this can improve first-frame speed",
    
    "hook.enable": "Whether to enable hook events. When enabled, both push and pull are authenticated",
    "hook.on_flow_report": "Traffic-usage event for players or pushers. Leave empty to disable",
    "hook.on_http_access": "HTTP file access authentication event. Leave empty to disable authentication",
    "hook.on_play": "Playback authentication event. Leave empty to disable authentication",
    "hook.on_publish": "Push authentication event. Leave empty to disable authentication",
    "hook.on_record_mp4": "MP4 segment recording completion event",
    "hook.on_record_ts": "HLS ts (or fmp4) segment recording completion event",
    "hook.on_rtsp_auth": "RTSP playback authentication event. The RTSP username and password are compared in this event",
    "hook.on_rtsp_realm": "Whether to enable the dedicated RTSP playback authentication event. Leave empty to disable RTSP authentication",
    "hook.on_shell_login": "Remote telnet debugging authentication event",
    "hook.on_stream_changed": "Live stream registration or deregistration event",
    "hook.stream_changed_schemas": "Filter the protocol types of the on_stream_changed hook; you can choose to listen only to protocols of interest. Leave empty to not filter protocols",
    "hook.on_stream_none_reader": "No-viewer stream event. Through this event, you can choose whether to close streams with no viewers",
    "hook.on_stream_not_found": "Stream-not-found event during playback. Combined with the hook.on_stream_none_reader event, on-demand stream pulling can be achieved",
    "hook.on_server_started": "Server startup report. Can be used to listen for server crash-restart events",
    "hook.on_server_exited": "Server exit report. Triggered when the server exits normally",
    "hook.on_server_keepalive": "Server keepalive report",
    "hook.on_send_rtp_stopped": "Callback when RTP sending (startSendRtp) is passively closed",
    "hook.on_rtp_server_timeout": "RTP server received no data within the timeout",
    "hook.timeoutSec": "Maximum time to wait for a hook API reply, in seconds",
    "hook.alive_interval": "Trigger interval of the keepalive hook, in seconds, float type",
    "hook.retry": "Number of retries when a hook notification fails, a positive integer. 0 means no retry, 1 means retry once, and so on",
    "hook.retry_delay": "Retry delay when a hook notification fails, in seconds, float type",
    
    "cluster.origin_url": "Origin pull URL template, formatted similarly to printf. The first %s specifies app, the second %s specifies stream_id",
    "cluster.timeout_sec": "Total origin-tracing timeout, in seconds, float type",
    "cluster.retry_count": "Number of origin-tracing retry attempts. -1 means retry forever",
    
    "http.charSet": "Character encoding set of the HTTP server",
    "http.keepAliveSecond": "HTTP connection timeout",
    "http.maxReqSize": "Maximum HTTP request body size in bytes. If the posted body is too large, it is not suitable to cache the body in memory",
    "http.notFound": "404 page content. Users can customize the 404 page",
    "http.port": "HTTP server listening port",
    "http.rootPath": "Root directory of the HTTP file server. Can be a relative (relative to this executable's directory) or absolute path",
    "http.sendBufSize": "Read-file cache size of the HTTP file server, in BYTE. Adjusting this parameter can optimize file I/O performance",
    "http.sslport": "HTTPS server listening port",
    "http.dirMenu": "Whether to display the folder menu. When enabled, folders can be browsed",
    "http.virtualPath": "Virtual directory. The virtual directory name and file path are separated by \",\", and multiple config paths are separated by \";\"",
    "http.forbidCacheSuffix": "File suffixes forbidden from using mmap cache, separated by \",\"",
    "http.forwarded_ip_header": "Allows placing the real client IP behind an HTTP proxy into an HTTP header",
    "http.allow_cross_domains": "All cross-origin requests are allowed by default",
    "http.allow_ip_range": "IP address range whitelist allowed to access the HTTP API and HTTP file index. No restriction when left empty",
    
    "multicast.addrMax": "End multicast IP address of the RTP multicast range",
    "multicast.addrMin": "Start multicast IP address of the RTP multicast range",
    "multicast.udpTTL": "Multicast UDP TTL",
    
    "record.appName": "App name for MP4 recording or MP4 VOD. Restricting the app name can prevent arbitrary VOD playback",
    "record.fileBufSize": "MP4 recording file-write cache, in BYTE. Adjusting this parameter can improve file I/O performance",
    "record.sampleMS": "Amount of data streamed per MP4 VOD pass, in milliseconds",
    "record.fastStart": "Whether to write a second keyframe index into the header after MP4 recording completes",
    "record.fileRepeat": "Whether MP4 VOD (rtsp/rtmp/http-flv/ws-flv) plays the file in a loop",
    "record.enableFmp4": "Whether MP4 recording uses the fmp4 file format. When enabled, files whose recording was interrupted by a power failure can still be opened normally",
    "record.max_delta_stamp_ms": "Maximum timestamp delta, in milliseconds",
    
    "rtmp.handshakeSecond": "RTMP must complete the handshake within this time, otherwise the server disconnects, in seconds",
    "rtmp.keepAliveSecond": "RTMP timeout. If no client data is received within this time, or the TCP send cache exceeds this time, the connection is disconnected, in seconds",
    "rtmp.port": "RTMP server listening port",
    "rtmp.sslport": "RTMPS server listening address",
    "rtmp.directProxy": "Whether RTMP uses direct proxy mode",
    "rtmp.enhanced": "Whether h265/opus/vp8/vp9/av1 RTMP packaging uses the enhanced RTMP standard or the domestic extended standard",
    
    "rtp.audioMtuSize": "Audio MTU size. This parameter limits the maximum RTP byte count; recommended not to exceed 1400",
    "rtp.videoMtuSize": "Video MTU size. This parameter limits the maximum RTP byte count; recommended not to exceed 1400",
    "rtp.rtpMaxSize": "Maximum RTP packet length limit, in KB. Mainly used to identify erroneous RTP obtained when the TCP context is corrupted",
    "rtp.lowLatency": "Low-latency switch for RTP packaging. Disabled by default",
    "rtp.h264_stap_a": "Whether the H264 RTP packaging mode uses stap-a mode",
    
    "rtp_proxy.dumpDir": "Export debug data (including rtp/ps/h264) to this directory. Leave empty to disable data export",
    "rtp_proxy.port": "UDP and TCP proxy server, supporting RTP proxy (must be ts or ps type)",
    "rtp_proxy.timeoutSec": "RTP timeout, in seconds",
    "rtp_proxy.port_range": "Random port range. Ensure at least 36 ports",
    "rtp_proxy.h264_pt": "PT of the RTP h264 payload",
    "rtp_proxy.h265_pt": "PT of the RTP h265 payload",
    "rtp_proxy.ps_pt": "PT of the RTP ps payload",
    "rtp_proxy.opus_pt": "PT of the RTP opus payload",
    "rtp_proxy.aac_pt": "PT of the RTP aac payload",
    "rtp_proxy.gop_cache": "Whether startSendRtp and startRecord related features enable GOP cache in advance to optimize the cascaded instant-start experience",
    "rtp_proxy.rtp_g711_dur_ms": "When packaging g711 RTP for the national standard, the voice duration of each packet. Defaults to 100 ms",
    "rtp_proxy.udp_recv_socket_buffer": "UDP receive socket buffer size configuration",
    "rtp_proxy.merge_frame": "Whether to wait for the next frame after ps/ts parsing to determine whether the current frame is complete",
    "rtp_proxy.force_tcp": "Whether to force the use of TCP mode to proxy RTP",
    
    "rtc.signalingPort": "WebRTC signaling server port",
    "rtc.signalingSslPort": "WebRTC SSL signaling server port",
    "rtc.icePort": "STUN/TURN server port",
    "rtc.iceTcpPort": "STUN/TURN TCP server port",
    "rtc.enableTurn": "Whether the STUN/TURN port enables the TURN service",
    "rtc.iceTransportPolicy": "ICE transport policy: 0 = no restriction (default), 1 = Relay forwarding only, 2 = P2P direct connection only",
    "rtc.iceUfrag": "ICE username of the STUN/TURN service",
    "rtc.icePwd": "ICE password of the STUN/TURN service",
    "rtc.datachannel_echo": "Whether the WebRTC datachannel echoes data, for testing",
    "rtc.max_stun_retry": "Maximum number of STUN retries",
    "rtc.port_range": "Port pool allocated by the TURN service",
    "rtc.timeoutSec": "RTC push and playback timeout",
    "rtc.externIP": "IP visible to RTC clients from this machine. As a server it is usually a public IP. There can be multiple, separated by ','",
    "rtc.interfaces": "When interfaces is specified, the ICE server will use the specified network interface to bind the socket",
    "rtc.port": "RTC UDP server listening port",
    "rtc.tcpPort": "RTC TCP server listening port",
    "rtc.rembBitRate": "Set the REMB bitrate. When non-zero, TWCC is disabled and REMB is enabled",
    "rtc.preferredCodecA": "Audio codec types supported by RTC. Those earlier in the list have higher priority",
    "rtc.preferredCodecV": "Video codec types supported by RTC. Those earlier in the list have higher priority",
    "rtc.start_bitrate": "WebRTC starting bitrate",
    "rtc.max_bitrate": "WebRTC maximum bitrate",
    "rtc.min_bitrate": "WebRTC minimum bitrate",
    "rtc.maxRtpCacheMS": "Maximum length of the RTP retransmission cache queue, in milliseconds",
    "rtc.maxRtpCacheSize": "Maximum length of the RTP retransmission cache queue, in count",
    "rtc.nackMaxSize": "Maximum number of retained RTP packet-loss states",
    "rtc.nackMaxMS": "Maximum retention time of RTP packet-loss states",
    "rtc.nackMaxCount": "Maximum number of NACK retransmission requests",
    "rtc.nackIntervalRatio": "NACK retransmission frequency, as a multiple of RTT",
    "rtc.nackRtpSize": "Number of video RTP packets in a video NACK packet",
    "rtc.nackAudioRtpSize": "Number of RTP packets in an audio NACK packet",
    "rtc.bfilter": "Whether to attempt filtering B-frames",
    "rtc.preferred_tcp": "Whether to prefer WebRTC over TCP mode",
    
    "srt.timeoutSec": "SRT push and playback timeout, in seconds",
    "srt.port": "SRT UDP server listening port",
    "srt.latencyMul": "Estimation parameter for the latency cache in the SRT protocol",
    "srt.pktBufSize": "Packet cache size",
    "srt.passPhrase": "Password of the SRT UDP server. Empty means no encryption",
    
    "rtsp.authBasic": "Whether the RTSP proprietary authentication method uses base64 or md5",
    "rtsp.directProxy": "Whether RTSP pull and push proxy use direct proxy mode",
    "rtsp.handshakeSecond": "RTSP must complete the handshake within this time, otherwise the server disconnects, in seconds",
    "rtsp.keepAliveSecond": "RTSP timeout. If no client data is received within this time, or the TCP send cache exceeds this time, the connection is disconnected, in seconds",
    "rtsp.port": "RTSP server listening address",
    "rtsp.sslport": "RTSPS server listening address",
    "rtsp.lowLatency": "Whether RTSP forwarding uses low-latency mode",
    "rtsp.rtpTransportType": "Force-negotiated RTP transport type (0: TCP, 1: UDP, 2: MULTICAST, -1: no restriction)",
    
    "shell.maxReqSize": "Maximum buffer size accepted by the debug telnet server",
    "shell.port": "Listening port of the debug telnet server",
    
    "onvif.port": "ONVIF search port",
    
    "1078.modify_audio_stamp": "Whether the 1078 protocol modifies the audio timestamp",
    "1078.add_audio_prefix": "Whether the 1078 protocol adds an audio prefix",
    "1078.check_payload_len": "Whether the 1078 protocol checks the payload length",
    
    "awss3.key": "AWS S3 access key",
    "awss3.secret": "AWS S3 access secret",
    "awss3.region": "AWS S3 region",
    "awss3.url": "AWS S3 service URL",
    
    "python.plugin": "Python plugin path"
};
